version: '2'

volumes:
  fcrepo:
  solr:
  db:
  redis:
  uploads:

services:
  solr:
    image: solr
    ports:
      - "${SOLR_PORT}:8983"
    volumes:
      - ../..:/app
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - hydra_production
      - /app/solr/config

  fcrepo:
    image: botimer/fcrepo:4.5.1
    volumes:
     - ../../fcrepo_io:/io  # Us can use this in development to save and restore fcrepo
     - fcrepo:/opt/data
    ports:
     - "${FCREPO_PORT}:8080"

  app:
    build: ../..
    environment:
      - REDIS_HOST=redis_primary
      - DATABASE_URL=postgresql://postgres@db/postgres
      - FEDORA_URL=http://fcrepo:8080/fcrepo/rest
      - SOLR_URL=http://solr:8983/solr/hydra_production
      - SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER=inline
      - SETTINGS__SOLR__URL=http://solr:8983/solr/hydra_production
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=asdf
#      - RAILS_CACHE_STORE_URL=memcache
    volumes:
      - ../../examples:/data/examples
      - ../..:/data  # You can do this to actively make changes in dev mode
      # - ./gems:/usr/local/bundle/gems  # This makes gems available outsite container
      - uploads:/data/public/uploads
    logging:
      driver: "json-file"
      options:
        max-size: 1m

  web:
    extends: app
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    depends_on:
      - db
      - solr
      - fcrepo
      - redis_primary
      - memcache
    ports:
      - "${PORT}:3000"


  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ../../Fc:/Fc  # For Backups and restores
    expose:
      - "5432"

  redis_primary:
    image: redis:3
    command: redis-server
    volumes:
      - redis:/data
    expose:
      - "6379"

  memcache:
    image: memcached
    expose:
      - "11211"
