development:
  admin:
    - qjhart@ucdavis.edu
    - jrmerz@ucdavis.edu
  archivist:
    - qjhart@ucdavis.edu
    - jrmerz@ucdavis.edu
  researcher:
    - qjhart@gmail.com
    - jrmerz@gmail.com
test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com

production: {}
